"use client";
import "./globals.css";
import store from "../redux/store";
import { Provider } from "react-redux";

export default function RootLayout({ children }) {
    return (
        <Provider store={store}>
            <html className="h-full" lang="en">
                <head>
                    <title>Wheelsdrive</title>
                    <meta
                        content="width=device-width, initial-scale=1"
                        name="viewport"
                    />
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/wheelsdrive-title.svg" />
                </head>
                <body className="h-full bg-background font-raleway">
                    {children}
                </body>
            </html>
        </Provider>
    );
}
